
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ALPHA = 12;
  public static final int TRANSICION = 3;
  public static final int ERROR = 13;
  public static final int FIN = 11;
  public static final int EOF = 0;
  public static final int PARENTESIS_ABRE = 8;
  public static final int ALFABETO = 4;
  public static final int SEPARADOR = 7;
  public static final int INICIAL = 5;
  public static final int error = 1;
  public static final int DELIMITADOR = 6;
  public static final int ESTADO = 10;
  public static final int PARENTESIS_CIERRA = 9;
  public static final int IDENTIFICADOR = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "TRANSICION",
  "ALFABETO",
  "INICIAL",
  "DELIMITADOR",
  "SEPARADOR",
  "PARENTESIS_ABRE",
  "PARENTESIS_CIERRA",
  "ESTADO",
  "FIN",
  "ALPHA",
  "ERROR"
  };
}

